name = "GibbsNearestNeighbourPointProcesses"
uuid = "ad934586-6619-43ef-a704-b28f1a866fc3"
authors = ["R cqls <rdrouilh@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoStatsProcesses = "aa102bde-5a27-4b0c-b2c1-e7a7dcc4c3e7"

[compat]
CairoMakie = "0.12.18"
DelaunayTriangulation = "1.6.3"
GeoStats = "0.72.0"
GeoStatsProcesses = "0.8.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
